CREATE TABLE [Lesson_Topic] (
	Id int NOT NULL IDENTITY(1,1),
	TopicId int NOT NULL,
	ClassId int NOT NULL,
  CONSTRAINT [PK_LESSON_TOPIC] PRIMARY KEY CLUSTERED
  (
  [Id] ASC
  ) WITH (IGNORE_DUP_KEY = OFF)

)
go

ALTER TABLE [Lesson_Topic] WITH CHECK ADD CONSTRAINT [Lesson_Topic_fk0] FOREIGN KEY ([TopicId]) REFERENCES [Topic]([Id])
ON UPDATE NO ACTION
GO
ALTER TABLE [Lesson_Topic] CHECK CONSTRAINT [Lesson_Topic_fk0]
GO
ALTER TABLE [Lesson_Topic] WITH CHECK ADD CONSTRAINT [Lesson_Topic_fk1] FOREIGN KEY ([ClassId]) REFERENCES [Lesson]([Id])
ON UPDATE NO ACTION
GO
ALTER TABLE [Lesson_Topic] CHECK CONSTRAINT [Lesson_Topic_fk1]
GO