CREATE TABLE [Tag_Topic] (
	Id int NOT NULL Identity,
	TagId int NOT NULL,
	TopicId int NOT NULL,
  CONSTRAINT [PK_TAG_TOPIC] PRIMARY KEY CLUSTERED
  (
  [Id] ASC
  ) WITH (IGNORE_DUP_KEY = OFF)

)
go

ALTER TABLE [Tag_Topic] WITH CHECK ADD CONSTRAINT [Tag_Topic_fk0] FOREIGN KEY ([TagId]) REFERENCES [Tag]([Id])
ON UPDATE NO ACTION
GO
ALTER TABLE [Tag_Topic] CHECK CONSTRAINT [Tag_Topic_fk0]
GO
ALTER TABLE [Tag_Topic] WITH CHECK ADD CONSTRAINT [Tag_Topic_fk1] FOREIGN KEY ([TopicId]) REFERENCES [Topic]([Id])
ON UPDATE NO ACTION
GO
ALTER TABLE [Tag_Topic] CHECK CONSTRAINT [Tag_Topic_fk1]
GO