CREATE TABLE [User_Role] (
	Id int NOT NULL IDENTITY(1,1),
	UserId int NOT NULL,
	RoleId int NOT NULL,
  CONSTRAINT [PK_USER_ROLE] PRIMARY KEY CLUSTERED
  (
  [Id] ASC
  ) WITH (IGNORE_DUP_KEY = OFF)

)
go

ALTER TABLE [User_Role] WITH CHECK ADD CONSTRAINT [User_Role_fk0] FOREIGN KEY ([UserId]) REFERENCES [User]([Id])
ON UPDATE NO ACTION
GO
ALTER TABLE [User_Role] CHECK CONSTRAINT [User_Role_fk0]
GO
ALTER TABLE [User_Role] WITH CHECK ADD CONSTRAINT [User_Role_fk1] FOREIGN KEY ([RoleId]) REFERENCES [Role]([Id])
ON UPDATE NO ACTION
GO
ALTER TABLE [User_Role] CHECK CONSTRAINT [User_Role_fk1]
GO